version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/audit-auth-app:1"
        LoadBalancerInfo:
          ContainerName: "audit-auth-app"
          ContainerPort: 9400